---
  - name: Do the system software upgrade
    hosts: all
    become: yes
    max_fail_percentage: 5

    tasks:
      - name: Upgrade all Debian packages
        apt: upgrade=dist update_cache=yes
        when: ansible_os_family == "Debian"
        notify: Reboot server

      - name: Upgrade all RedHat packages
        yum: name=* state=latest
        when: ansible_os_family == "RedHat"
        notify: Reboot server

    handlers:
      - name: Reboot server
        command: /sbin/shutdown -r +1
        async: 0
        poll: 0

      - name: Wait for the server to finish rebooting
        become: no
        local_action: wait_for host="{{ inventory_hostname }}" state=started
...
